/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#define STM32F411xE
#include <stdint.h>
#include "stm32f4xx.h"
#include "sub_function.h"

#define THRESHOLD 1333333

int main(void) {
	RCC->AHB1ENR |= (RCC_AHB1ENR_GPIOCEN+RCC_AHB1ENR_GPIOBEN+RCC_AHB1ENR_GPIOAEN);

   while(1) {
	   for (int i = 0; i <= 5; i++) {
		   seven_segment(i);
		   for(uint32_t iter =0; iter < THRESHOLD; iter++) {}
	   }
   return 0;
   }
}
